### ISSUE TITLE
unity vlcplayer for android

### ISSUE THREAD

**Issue by giubri91** [bosqmode/UnityVLCPlayer#1]
hi i'm trying to develop an android rtsp video player on unity, and i'm using your repository to develop. I managed to make it work on windows, while if I try to switch platforms on android and compile it gives me several errors. Can you give me directions on how to compile for android? I suppose that it is necessary to copy an android version in the Plugins folder as is done for Windows, I have made some attempts but they have not gone well. I hope you can help me, thanks

**Comment by bosqmode** [comment]
Unfortunately I have no clue of dlls/wrappers and Android.
