### ISSUE TITLE
EntryPointNotFoundException: libvlc_media_tracks_get

### ISSUE THREAD

**Issue by hanselkoh** [bosqmode/UnityVLCPlayer#2]
Just wonder if anyone else had the same error?

I am using 2019.4.11, and have tested my rtsp link on a pc version vlc player to ensure if its working.

EntryPointNotFoundException: libvlc_media_tracks_get
bosqmode.libvlc.VLCPlayer.GetVideoTrack () (at Assets/UnityVLCPlayer/VLCPlayer.cs:168)
bosqmode.libvlc.VLCPlayer.TrackReaderThread () (at Assets/UnityVLCPlayer/VLCPlayer.cs:111)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ThreadHelper.ThreadStart () (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)
bosqmode.libvlc.LibVLCWrapper:libvlc_media_tracks_get(IntPtr, IntPtr&)
bosqmode.libvlc.VLCPlayer:GetVideoTrack() (at Assets/UnityVLCPlayer/VLCPlayer.cs:168)
bosqmode.libvlc.VLCPlayer:TrackReaderThread() (at Assets/UnityVLCPlayer/VLCPlayer.cs:111)
System.Threading.ThreadHelper:ThreadStart()

**Comment by bosqmode** [comment]
Seems like the libvlc_media_tracks_get() is not found in libvlc.dll, have tried with the 4.0.0 nightly version that I had when I wrote the readme?

**Comment by hanselkoh** [comment]
Thanks for getting back! I tried using 2021.2.11 as well, and did setup the folder as per the readme, not sure if there is a different with the plugin folder for 2019 and 2021.


![Screenshot 2023-10-25 230656](https://github.com/bosqmode/UnityVLCPlayer/assets/9311403/f45c79e8-a661-4fd5-8c14-23f06ea265df)
![Screenshot 2023-10-25 230719](https://github.com/bosqmode/UnityVLCPlayer/assets/9311403/a2bdc033-007c-4bd0-a6e6-a31f3fba11d1)

**Comment by bosqmode** [comment]
Looking through the documentation here: https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc.html, it looks like the method libvlc_media_tracks_get() does not exist anymore.

**Comment by bosqmode** [comment]
Downloading the release version of libvlc seemed to work: https://artifacts.videolan.org/vlc/release-win64/. Also upgraded the project to 2021 and still seems to be functioning fine. (Also updated the repo.)

**Comment by hanselkoh** [comment]
Thanks @bosqmode for the updates, the current is working.
